export const APP_CONFIG = {
  timezone: "Europe/Copenhagen",
  defaultTheme: "teal",
  themes: {
    teal: {
      label: "Teal",
      labelArabic: "الفيروزي",
      logo: "assets/logo-teal.png",
    },
    muharram: {
      label: "Muharram",
      labelArabic: "محرم",
      logo: "assets/logo-red.png",
    },
  },
  storageKeys: {
    prayerTimes: "imamAliDisplay.prayerTimes",
    events: "imamAliDisplay.events",
    theme: "imamAliDisplay.theme",
  },
  prayerOrder: ["fajr", "sunrise", "dhuhr", "asr", "maghrib", "isha"],
  countdownPrayerKeys: ["fajr", "dhuhr", "asr", "maghrib", "isha"],
  prayerMeta: {
    fajr: { arabic: "الفجر", danish: "Fajr", icon: "moon" },
    sunrise: { arabic: "الشروق", danish: "Solopgang", icon: "sunrise" },
    dhuhr: { arabic: "الظهر", danish: "Middag", icon: "sun" },
    asr: { arabic: "العصر", danish: "Eftermiddag", icon: "asr" },
    maghrib: { arabic: "المغرب", danish: "Maghrib", icon: "sunset" },
    isha: { arabic: "العشاء", danish: "Nat", icon: "night" },
  },
  samplePaths: {
    prayerTimes: "data/prayer-times.sample.json",
    events: "data/events.sample.json",
  },
  apiPaths: {
    todayPrayerTimes: "/.netlify/functions/today-prayer-times",
    upcomingEvent: "/.netlify/functions/upcoming-event",
  },
  footerMessages: {
    teal: {
      arabic: "مرحباً بكم - نسعد بزيارتكم",
      danish: "Alle er velkomne - Vi glæder os til at se dig",
    },
    muharram: {
      arabic: "السلام عليك يا أبا عبد الله الحسين",
      danish: "Fred være med dig, o Abu Abdullah al-Hussein",
    },
  },
  bannerContexts: {
    teal: {
      arabic: "صلاة الجمعة",
      danish: "Fredagsbøn",
      metaArabic: "الجمعة - 13:30",
      metaDanish: "Fredag - 13:30",
      tagArabic: "البرنامج الأسبوعي",
      tagDanish: "Weekly program",
    },
    muharram: {
      arabic: "شهر محرم الحرام",
      danish: "Muharram 1448",
      metaArabic: "برنامج المجالس والفعاليات",
      metaDanish: "Majalis og særlige begivenheder",
      tagArabic: "محرم",
      tagDanish: "Muharram",
    },
  },
  headlineFallbacks: {
    teal: {
      titleArabic: "صلاة الجمعة",
      titleDanish: "Fredagsbøn (Jumu'ah)",
      descriptionArabic: "جدول اليوم معروض مباشرة من شاشة المسجد",
      descriptionDanish: "Dagens skema vises direkte på moskéens skærm",
      tagArabic: "البرنامج اليومي",
      tagDanish: "Dagsprogram",
    },
    muharram: {
      titleArabic: "شهر محرم الحرام",
      titleDanish: "Muharram al-Haram",
      descriptionArabic: "نسخة محرم المهيأة للمجالس والفعاليات الخاصة",
      descriptionDanish: "Muharram-version klargjort til majalis og særlige arrangementer",
      tagArabic: "محرم 1448",
      tagDanish: "Muharram 1448",
    },
  },
  noticeMessages: {
    teal: {
      titleArabic: "ابقَ على اطلاع",
      titleDanish: "Hold dig opdateret",
      bodyArabic: "تابع الأحداث القادمة على موقعنا ووسائل التواصل الاجتماعي.",
      bodyDanish: "Følg med i kommende begivenheder på vores hjemmeside og sociale medier.",
    },
    muharram: {
      titleArabic: "ذكرى محرم",
      titleDanish: "Muharram påmindelse",
      bodyArabic: "نسخة محرم مهيأة للمجالس والفعاليات الخاصة وإحياء الذكرى.",
      bodyDanish: "Muharram-layoutet er klargjort til majalis og særlige mindehøjtideligheder.",
    },
  },
};

export const SAMPLE_PRAYER_TIMES = [
  {
    date: "2026-06-09",
    hijriDateArabic: "23 ذو الحجة 1447 هـ",
    hijriDateLatin: "23 Dhu al-Hijjah 1447 H",
    fajr: "02:29",
    sunrise: "04:28",
    dhuhr: "13:09",
    asr: "17:39",
    maghrib: "21:51",
    isha: "23:43",
  },
  {
    date: "2026-06-10",
    hijriDateArabic: "24 ذو الحجة 1447 هـ",
    hijriDateLatin: "24 Dhu al-Hijjah 1447 H",
    fajr: "02:28",
    sunrise: "04:27",
    dhuhr: "13:09",
    asr: "17:40",
    maghrib: "21:52",
    isha: "23:44",
  },
  {
    date: "2026-06-11",
    hijriDateArabic: "25 ذو الحجة 1447 هـ",
    hijriDateLatin: "25 Dhu al-Hijjah 1447 H",
    fajr: "02:27",
    sunrise: "04:27",
    dhuhr: "13:09",
    asr: "17:40",
    maghrib: "21:53",
    isha: "23:45",
  },
  {
    date: "2026-06-12",
    hijriDateArabic: "26 ذو الحجة 1447 هـ",
    hijriDateLatin: "26 Dhu al-Hijjah 1447 H",
    fajr: "02:26",
    sunrise: "04:26",
    dhuhr: "13:10",
    asr: "17:41",
    maghrib: "21:54",
    isha: "23:46",
  },
  {
    date: "2026-06-13",
    hijriDateArabic: "27 ذو الحجة 1447 هـ",
    hijriDateLatin: "27 Dhu al-Hijjah 1447 H",
    fajr: "02:25",
    sunrise: "04:26",
    dhuhr: "13:10",
    asr: "17:41",
    maghrib: "21:55",
    isha: "23:47",
  },
  {
    date: "2026-06-14",
    hijriDateArabic: "28 ذو الحجة 1447 هـ",
    hijriDateLatin: "28 Dhu al-Hijjah 1447 H",
    fajr: "02:24",
    sunrise: "04:26",
    dhuhr: "13:10",
    asr: "17:42",
    maghrib: "21:56",
    isha: "23:48",
  },
  {
    date: "2026-06-15",
    hijriDateArabic: "29 ذو الحجة 1447 هـ",
    hijriDateLatin: "29 Dhu al-Hijjah 1447 H",
    fajr: "02:24",
    sunrise: "04:26",
    dhuhr: "13:10",
    asr: "17:42",
    maghrib: "21:57",
    isha: "23:48",
  },
];

export const SAMPLE_EVENTS = [
  {
    id: "event-001",
    titleArabic: "صلاة الجمعة",
    titleDanish: "Fredagsbøn (Jumu'ah)",
    date: "2026-06-12",
    time: "13:30",
    locationArabic: "الجامع الرئيسي",
    locationDanish: "Hovedmoskeen",
    descriptionArabic: "مرحباً بكم - نسعد بزيارتكم",
    descriptionDanish: "Alle er velkomne - Vi glæder os til at se dig",
    theme: "teal",
    active: true,
  },
  {
    id: "event-002",
    titleArabic: "مجلس الليلة الأولى من محرم",
    titleDanish: "Majlis – første aften af Muharram",
    date: "2026-06-13",
    time: "19:30",
    locationArabic: "الجامع الرئيسي",
    locationDanish: "Hovedmoskeen",
    descriptionArabic: "ذكرى استشهاد الإمام الحسين عليه السلام",
    descriptionDanish: "Mindehøjtidelighed for Imam Hussein",
    theme: "muharram",
    active: true,
  },
];
