export const APP_CONFIG = {
  timezone: "Europe/Copenhagen",
  defaultTheme: "teal",
  prayerDisplayMode: "imamAliCopenhagen",
  themes: {
    teal: {
      label: "Teal",
      labelArabic: "الفيروزي",
      logo: "assets/logo-teal.png",
    },
    muharram: {
      label: "Muharram",
      labelArabic: "محرم",
      logo: "assets/logo-red.png",
    },
  },
  eventCategories: {
    normal: {
      label: "Normal",
      labelArabic: "عادي",
      labelDanish: "Normal",
      placeholderArabic: "فعالية المسجد",
      placeholderDanish: "Moské-arrangement",
      symbol: "N",
      displayThemes: ["teal"],
    },
    muharram: {
      label: "Muharram",
      labelArabic: "محرم",
      labelDanish: "Muharram",
      placeholderArabic: "فعالية محرم",
      placeholderDanish: "Muharram-arrangement",
      symbol: "M",
      displayThemes: ["muharram"],
    },
    ramadan: {
      label: "Ramadan",
      labelArabic: "رمضان",
      labelDanish: "Ramadan",
      placeholderArabic: "برنامج رمضان",
      placeholderDanish: "Ramadan-program",
      symbol: "R",
      displayThemes: ["teal"],
    },
    eid: {
      label: "Eid",
      labelArabic: "عيد",
      labelDanish: "Eid",
      placeholderArabic: "فعالية العيد",
      placeholderDanish: "Eid-arrangement",
      symbol: "E",
      displayThemes: ["teal"],
    },
    majlis: {
      label: "Majlis",
      labelArabic: "مجلس",
      labelDanish: "Majlis",
      placeholderArabic: "مجلس",
      placeholderDanish: "Majlis",
      symbol: "J",
      displayThemes: ["teal", "muharram"],
    },
    friday: {
      label: "Friday prayer",
      labelArabic: "الجمعة",
      labelDanish: "Fredagsbøn",
      placeholderArabic: "صلاة الجمعة",
      placeholderDanish: "Fredagsbøn",
      symbol: "F",
      displayThemes: ["teal"],
    },
  },
  storageKeys: {
    prayerTimes: "imamAliDisplay.prayerTimes",
    events: "imamAliDisplay.events",
    theme: "imamAliDisplay.theme",
  },
  prayerFields: ["fajr", "sunrise", "dhuhr", "asr", "sunset", "maghrib", "isha", "midnight"],
  prayerDisplayModes: {
    standard: {
      order: ["fajr", "sunrise", "dhuhr", "asr", "maghrib", "isha"],
      countdownOrder: ["fajr", "sunrise", "dhuhr", "asr", "maghrib", "isha"],
      labels: {
        fajr: { arabic: "الفجر", danish: "Fajr" },
        sunrise: { arabic: "الشروق", danish: "Solopgang" },
        dhuhr: { arabic: "الظهر", danish: "Middag" },
        asr: { arabic: "العصر", danish: "Eftermiddag" },
        maghrib: { arabic: "المغرب", danish: "Maghrib" },
        isha: { arabic: "العشاء", danish: "Nat" },
      },
    },
    imamAliCopenhagen: {
      order: ["fajr", "sunrise", "dhuhr", "sunset", "maghrib", "midnight"],
      countdownOrder: ["fajr", "sunrise", "dhuhr", "sunset", "maghrib", "midnight"],
      labels: {
        fajr: { arabic: "الصبح", danish: "Subh" },
        sunrise: { arabic: "الشروق", danish: "Solopgang" },
        dhuhr: { arabic: "الظهر", danish: "Dhuhr" },
        sunset: { arabic: "الغروب", danish: "Solnedgang" },
        maghrib: { arabic: "المغرب", danish: "Maghrib" },
        midnight: { arabic: "منتصف الليل", danish: "Midnat" },
      },
    },
  },
  prayerMeta: {
    fajr: { icon: "moon" },
    sunrise: { icon: "sunrise" },
    dhuhr: { icon: "sun" },
    asr: { icon: "asr" },
    sunset: { icon: "sunset" },
    maghrib: { icon: "sunset" },
    isha: { icon: "night" },
    midnight: { icon: "midnight" },
  },
  samplePaths: {
    prayerTimes: "data/prayer-times.sample.json",
    events: "data/events.sample.json",
  },
  apiPaths: {
    todayPrayerTimes: "/.netlify/functions/get-today-prayer-times",
    upcomingEvent: "/.netlify/functions/get-upcoming-event",
    adminPrayerTimes: "/.netlify/functions/get-admin-prayer-times",
    adminEvents: "/.netlify/functions/get-admin-events",
    savePrayerTimes: "/.netlify/functions/save-prayer-times",
    saveEvent: "/.netlify/functions/save-event",
    archiveEvent: "/.netlify/functions/archive-event",
    deleteEvent: "/.netlify/functions/delete-event",
    restoreEvent: "/.netlify/functions/restore-event",
    restorePrayerTimes: "/.netlify/functions/restore-prayer-times",
    permanentlyDeleteEvent: "/.netlify/functions/permanently-delete-event",
    permanentlyDeletePrayerTimes: "/.netlify/functions/permanently-delete-prayer-times",
  },
  syncMessages: {
    connected: "Connected to Supabase. Updates will sync to mosque screens.",
    localOnly: "Saved locally only. This will not update other screens until Supabase is connected.",
    saveError: "Error saving to Supabase. Please check Netlify environment variables.",
    unavailable: "Supabase unavailable. Changes are saved locally only.",
  },
  footerMessages: {
    teal: {
      arabic: "مرحباً بكم - نسعد بزيارتكم",
      danish: "Alle er velkomne - Vi glæder os til at se dig",
    },
    muharram: {
      arabic: "السلام عليك يا أبا عبد الله الحسين",
      danish: "Fred være med dig, o Abu Abdullah al-Hussein",
    },
  },
  bannerContexts: {
    teal: {
      arabic: "صلاة الجمعة",
      danish: "Fredagsbøn",
      metaArabic: "الجمعة - 13:30",
      metaDanish: "Fredag - 13:30",
      tagArabic: "البرنامج الأسبوعي",
      tagDanish: "Weekly program",
    },
    muharram: {
      arabic: "شهر محرم الحرام",
      danish: "Muharram 1448",
      metaArabic: "برنامج المجالس والفعاليات",
      metaDanish: "Majalis og særlige begivenheder",
      tagArabic: "محرم",
      tagDanish: "Muharram",
    },
  },
  headlineFallbacks: {
    teal: {
      titleArabic: "صلاة الجمعة",
      titleDanish: "Fredagsbøn (Jumu'ah)",
      descriptionArabic: "جدول اليوم معروض مباشرة من شاشة المسجد",
      descriptionDanish: "Dagens skema vises direkte på moskéens skærm",
      tagArabic: "البرنامج اليومي",
      tagDanish: "Dagsprogram",
    },
    muharram: {
      titleArabic: "شهر محرم الحرام",
      titleDanish: "Muharram al-Haram",
      descriptionArabic: "نسخة محرم المهيأة للمجالس والفعاليات الخاصة",
      descriptionDanish: "Muharram-version klargjort til majalis og særlige arrangementer",
      tagArabic: "محرم 1448",
      tagDanish: "Muharram 1448",
    },
  },
  noticeMessages: {
    teal: {
      titleArabic: "ابقَ على اطلاع",
      titleDanish: "Hold dig opdateret",
      bodyArabic: "تابع الأحداث القادمة على موقعنا ووسائل التواصل الاجتماعي.",
      bodyDanish: "Følg med i kommende begivenheder på vores hjemmeside og sociale medier.",
    },
    muharram: {
      titleArabic: "ذكرى محرم",
      titleDanish: "Muharram påmindelse",
      bodyArabic: "نسخة محرم مهيأة للمجالس والفعاليات الخاصة وإحياء الذكرى.",
      bodyDanish: "Muharram-layoutet er klargjort til majalis og særlige mindehøjtideligheder.",
    },
  },
  prayerMessages: {
    missingToday: {
      arabic: "بيانات اليوم غير متوفرة",
      danish: "Dagens bønnetider mangler",
    },
    missingTodayDetail: {
      arabic: "لا توجد مواقيت محفوظة لتاريخ اليوم.",
      danish: "Der findes ingen gemte bønnetider for dagens dato.",
    },
    dayCompleted: {
      arabic: "انتهت صلوات اليوم",
      danish: "Dagens bønner er afsluttet",
    },
    countdownUnavailable: {
      arabic: "--س --د --ث",
      danish: "--t --m --s",
    },
    invalidTime: {
      arabic: "وقت غير صالح",
      danish: "Ugyldig tid",
    },
  },
  eventMessages: {
    noneUpcoming: {
      arabic: "لا توجد فعاليات قادمة حالياً",
      danish: "Der er ingen kommende begivenheder lige nu",
    },
    noneUpcomingDetail: {
      arabic: "سيتم عرض الفعالية التالية عند إضافتها وتفعيلها.",
      danish: "Den næste begivenhed vises her, når den er tilføjet og aktiv.",
    },
  },
};

export const SAMPLE_PRAYER_TIMES = [
  {
    date: "2026-06-09",
    hijriDateArabic: "23 ذو الحجة 1447 هـ",
    hijriDateLatin: "23 Dhu al-Hijjah 1447 H",
    fajr: "02:29",
    sunrise: "04:28",
    dhuhr: "13:09",
    asr: "17:39",
    sunset: "21:11",
    maghrib: "21:51",
    isha: "23:43",
    midnight: "23:50",
  },
  {
    date: "2026-06-10",
    hijriDateArabic: "24 ذو الحجة 1447 هـ",
    hijriDateLatin: "24 Dhu al-Hijjah 1447 H",
    fajr: "02:28",
    sunrise: "04:27",
    dhuhr: "13:09",
    asr: "17:40",
    sunset: "21:12",
    maghrib: "21:52",
    isha: "23:44",
    midnight: "23:51",
  },
  {
    date: "2026-06-11",
    hijriDateArabic: "25 ذو الحجة 1447 هـ",
    hijriDateLatin: "25 Dhu al-Hijjah 1447 H",
    fajr: "02:27",
    sunrise: "04:27",
    dhuhr: "13:09",
    asr: "17:40",
    sunset: "21:13",
    maghrib: "21:53",
    isha: "23:45",
    midnight: "23:52",
  },
  {
    date: "2026-06-12",
    hijriDateArabic: "26 ذو الحجة 1447 هـ",
    hijriDateLatin: "26 Dhu al-Hijjah 1447 H",
    fajr: "02:26",
    sunrise: "04:26",
    dhuhr: "13:10",
    asr: "17:41",
    sunset: "21:14",
    maghrib: "21:54",
    isha: "23:46",
    midnight: "23:53",
  },
  {
    date: "2026-06-13",
    hijriDateArabic: "27 ذو الحجة 1447 هـ",
    hijriDateLatin: "27 Dhu al-Hijjah 1447 H",
    fajr: "02:25",
    sunrise: "04:26",
    dhuhr: "13:10",
    asr: "17:41",
    sunset: "21:15",
    maghrib: "21:55",
    isha: "23:47",
    midnight: "23:54",
  },
  {
    date: "2026-06-14",
    hijriDateArabic: "28 ذو الحجة 1447 هـ",
    hijriDateLatin: "28 Dhu al-Hijjah 1447 H",
    fajr: "02:24",
    sunrise: "04:26",
    dhuhr: "13:10",
    asr: "17:42",
    sunset: "21:16",
    maghrib: "21:56",
    isha: "23:48",
    midnight: "23:55",
  },
  {
    date: "2026-06-15",
    hijriDateArabic: "29 ذو الحجة 1447 هـ",
    hijriDateLatin: "29 Dhu al-Hijjah 1447 H",
    fajr: "02:24",
    sunrise: "04:26",
    dhuhr: "13:10",
    asr: "17:42",
    sunset: "21:17",
    maghrib: "21:57",
    isha: "23:48",
    midnight: "23:56",
  },
  {
    date: "2026-07-01",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:44",
    sunrise: "04:30",
    dhuhr: "13:14",
    asr: "",
    sunset: "21:56",
    maghrib: "22:37",
    isha: "",
    midnight: "23:50",
  },
  {
    date: "2026-07-02",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:44",
    sunrise: "04:31",
    dhuhr: "13:14",
    asr: "",
    sunset: "21:56",
    maghrib: "22:36",
    isha: "",
    midnight: "23:50",
  },
  {
    date: "2026-07-03",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:44",
    sunrise: "04:32",
    dhuhr: "13:14",
    asr: "",
    sunset: "21:55",
    maghrib: "22:35",
    isha: "",
    midnight: "23:50",
  },
  {
    date: "2026-07-04",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:44",
    sunrise: "04:33",
    dhuhr: "13:14",
    asr: "",
    sunset: "21:55",
    maghrib: "22:35",
    isha: "",
    midnight: "23:50",
  },
  {
    date: "2026-07-05",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:44",
    sunrise: "04:34",
    dhuhr: "13:14",
    asr: "",
    sunset: "21:54",
    maghrib: "22:34",
    isha: "",
    midnight: "23:49",
  },
  {
    date: "2026-07-06",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:45",
    sunrise: "04:35",
    dhuhr: "13:14",
    asr: "",
    sunset: "21:53",
    maghrib: "22:33",
    isha: "",
    midnight: "23:49",
  },
  {
    date: "2026-07-07",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:45",
    sunrise: "04:36",
    dhuhr: "13:15",
    asr: "",
    sunset: "21:52",
    maghrib: "22:32",
    isha: "",
    midnight: "23:49",
  },
  {
    date: "2026-07-08",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:45",
    sunrise: "04:37",
    dhuhr: "13:15",
    asr: "",
    sunset: "21:52",
    maghrib: "22:31",
    isha: "",
    midnight: "23:48",
  },
  {
    date: "2026-07-09",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:45",
    sunrise: "04:39",
    dhuhr: "13:15",
    asr: "",
    sunset: "21:51",
    maghrib: "22:30",
    isha: "",
    midnight: "23:48",
  },
  {
    date: "2026-07-10",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:45",
    sunrise: "04:40",
    dhuhr: "13:15",
    asr: "",
    sunset: "21:50",
    maghrib: "22:28",
    isha: "",
    midnight: "23:48",
  },
  {
    date: "2026-07-11",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:45",
    sunrise: "04:41",
    dhuhr: "13:15",
    asr: "",
    sunset: "21:49",
    maghrib: "22:27",
    isha: "",
    midnight: "23:47",
  },
  {
    date: "2026-07-12",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:46",
    sunrise: "04:42",
    dhuhr: "13:15",
    asr: "",
    sunset: "21:48",
    maghrib: "22:26",
    isha: "",
    midnight: "23:47",
  },
  {
    date: "2026-07-13",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:46",
    sunrise: "04:44",
    dhuhr: "13:15",
    asr: "",
    sunset: "21:46",
    maghrib: "22:24",
    isha: "",
    midnight: "23:46",
  },
  {
    date: "2026-07-14",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:46",
    sunrise: "04:45",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:45",
    maghrib: "22:23",
    isha: "",
    midnight: "23:46",
  },
  {
    date: "2026-07-15",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:46",
    sunrise: "04:47",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:44",
    maghrib: "22:21",
    isha: "",
    midnight: "23:45",
  },
  {
    date: "2026-07-16",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:46",
    sunrise: "04:48",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:43",
    maghrib: "22:20",
    isha: "",
    midnight: "23:44",
  },
  {
    date: "2026-07-17",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:46",
    sunrise: "04:50",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:41",
    maghrib: "22:18",
    isha: "",
    midnight: "23:44",
  },
  {
    date: "2026-07-18",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:46",
    sunrise: "04:51",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:40",
    maghrib: "22:16",
    isha: "",
    midnight: "23:43",
  },
  {
    date: "2026-07-19",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:46",
    sunrise: "04:53",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:38",
    maghrib: "22:15",
    isha: "",
    midnight: "23:42",
  },
  {
    date: "2026-07-20",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:46",
    sunrise: "04:54",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:37",
    maghrib: "22:13",
    isha: "",
    midnight: "23:42",
  },
  {
    date: "2026-07-21",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:46",
    sunrise: "04:56",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:35",
    maghrib: "22:11",
    isha: "",
    midnight: "23:41",
  },
  {
    date: "2026-07-22",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:46",
    sunrise: "04:58",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:34",
    maghrib: "22:09",
    isha: "",
    midnight: "23:40",
  },
  {
    date: "2026-07-23",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:46",
    sunrise: "04:59",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:32",
    maghrib: "22:07",
    isha: "",
    midnight: "23:39",
  },
  {
    date: "2026-07-24",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:47",
    sunrise: "05:01",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:31",
    maghrib: "22:06",
    isha: "",
    midnight: "23:39",
  },
  {
    date: "2026-07-25",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:47",
    sunrise: "05:03",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:29",
    maghrib: "22:04",
    isha: "",
    midnight: "23:38",
  },
  {
    date: "2026-07-26",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:47",
    sunrise: "05:04",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:27",
    maghrib: "22:02",
    isha: "",
    midnight: "23:37",
  },
  {
    date: "2026-07-27",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:47",
    sunrise: "05:06",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:25",
    maghrib: "21:59",
    isha: "",
    midnight: "23:36",
  },
  {
    date: "2026-07-28",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:47",
    sunrise: "05:08",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:23",
    maghrib: "21:57",
    isha: "",
    midnight: "23:35",
  },
  {
    date: "2026-07-29",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:47",
    sunrise: "05:10",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:22",
    maghrib: "21:55",
    isha: "",
    midnight: "23:34",
  },
  {
    date: "2026-07-30",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:47",
    sunrise: "05:11",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:20",
    maghrib: "21:53",
    isha: "",
    midnight: "23:33",
  },
  {
    date: "2026-07-31",
    hijriDateArabic: "",
    hijriDateLatin: "",
    fajr: "01:46",
    sunrise: "05:13",
    dhuhr: "13:16",
    asr: "",
    sunset: "21:18",
    maghrib: "21:51",
    isha: "",
    midnight: "23:32",
  },
];

export const SAMPLE_EVENTS = [
  {
    id: "event-001",
    titleArabic: "صلاة الجمعة",
    titleDanish: "Fredagsbøn (Jumu'ah)",
    date: "2026-06-12",
    time: "13:30",
    locationArabic: "الجامع الرئيسي",
    locationDanish: "Hovedmoskeen",
    descriptionArabic: "مرحباً بكم - نسعد بزيارتكم",
    descriptionDanish: "Alle er velkomne - Vi glæder os til at se dig",
    theme: "friday",
    active: true,
  },
  {
    id: "event-002",
    titleArabic: "مجلس الليلة الأولى من محرم",
    titleDanish: "Majlis – første aften af Muharram",
    date: "2026-06-13",
    time: "19:30",
    locationArabic: "الجامع الرئيسي",
    locationDanish: "Hovedmoskeen",
    descriptionArabic: "ذكرى استشهاد الإمام الحسين عليه السلام",
    descriptionDanish: "Mindehøjtidelighed for Imam Hussein",
    theme: "muharram",
    active: true,
  },
];
